# Generated by Django 5.1.3 on 2025-01-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_fio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fio',
            new_name='user',
        ),
    ]
