# Generated by Django 5.1.3 on 2025-01-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_fio_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='fio',
        ),
    ]
