# Generated by Django 5.1.3 on 2025-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_edited_at_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.IntegerField(default=0),
        ),
    ]
